[api]
url_zeki = "http://homeassistant-students.intern.zeki:8123/api/states"
token = "Bearer ***"
content_type = "application/json"

[influxdb]
host = "10.42.2.20"
port = 8086
username = "***"
password = "***"
dbname = "home_assistant"